export const products = [
    {
        id: 1,
        description: "A classic white t-shirt with a crew neck.",
        title: "White T-Shirt",
        price: 1599,
        oldPrice: 2999,
        url: "https://picsum.photos/200/300",
    },
    {
        id: 2,
        description: "A pair of blue jeans with a straight leg.",
        title: "Blue Jeans",
        price: 2999,
        oldPrice: 4999,
        url: "https://picsum.photos/200/300",
    },
    {
        id: 3,
        description: "A black leather jacket with a biker style.",
        title: "Black Leather Jacket",
        price: 5999,
        oldPrice: 6999,
        url: "https://picsum.photos/200/300",
    },
    {
        id: 4,
        description: "A pair of red high heels with a stiletto heel.",
        title: "Red High Heels",
        price: 9999,
        oldPrice: 12499,
        url: "https://picsum.photos/200/300",
    },
    {
        id: 5,
        description: "A pair of black sneakers with a running style.",
        title: "Black Sneakers",
        price: 4999,
        oldPrice: 7599,
        url: "https://picsum.photos/200/300",
    },
    {
        id: 6,
        description: "A green dress with a floral print.",
        title: "Green Floral Dress",
        price: 6999,
        oldPrice: 9099,
        url: "https://picsum.photos/200/300",
    },
    {
        id: 7,
        description: "A white button-down shirt with a long sleeve.",
        title: "White Button-Down Shirt",
        price: 2599,
        oldPrice: 3099,
        url: "https://picsum.photos/200/300",
    },
    {
        id: 8,
        description: "A pair of black pants with a slim fit.",
        title: "Black Pants",
        price: 3999,
        oldPrice: 4999,
        url: "https://picsum.photos/200/300",
    },
    {
        id: 9,
        description: "A pair of brown leather boots with a lug sole.",
        title: "Brown Leather Boots",
        price: 7999,
        oldPrice: 9999,
        url: "https://picsum.photos/200/300",
    },
    {
        id: 10,
        description: "A black winter coat with a fur-lined hood.",
        title: "Black Winter Coat",
        price: 12999,
        oldPrice: 14999,
        url: "https://picsum.photos/200/300",
    },
];
